angular.module('definicionesModule', []) 

.controller ('definicionesController', ['$scope', function($scope) { 
  // Lista de definiciones
  $scope.definiciones = [
    {palabra:"Supino", definicion:"Necio, ignorante."},
    {palabra:"Estólido", definicion:"Falto de razón y discuros."},
    {palabra:"Estoicismo", definicion:"Dominio sobre la propia sensibilidad."},
    {palabra:"Ecuánime", definicion:"Constante en ánimo."},
    {palabra:"Antinomia", definicion:"Contradicción irresoluble."},
    {palabra:"Paradoja / Antilogía", definicion:"Idea extraña opuesta a la realidad."},
    {palabra:"Axioma", definicion:"Teoría que no puede refutarse."},
    {palabra:"Aforismo", definicion:"Regla en una ciencia o arte ( similar a Axioma pero basado en la práctica )."},
    {palabra:"Intelección", definicion:"Acción y efecto de entender."},
    {palabra:"Ulterior", definicion:"Que se produce después de una cosa."},
    {palabra:"Melómano", definicion:"Fanático de la música."},
    {palabra:"Peyorativo", definicion:"Expresión desfavorable."},
    {palabra:"Dádiva", definicion:"Algo que se da con gratuidad."},
    {palabra:"Epíteto", definicion:"Adjetivo que denota una cualidad prototípica del sustantivo al que modifica y que no ejerce función restrictiva.En la blanca nieve, blanca es un epíteto. / Palabra o sintagma fijo que tienen una función caracterizadora de personas o cosas. El rey Pedro I tuvo el epíteto de El Cruel. / Expresión calificativa usada como elogio o, más frecuentemente, como insulto. En la discusión se oyeron los más variados epítetos."},
    {palabra:"Magnanimidad", definicion:"Grandeza."},
    {palabra:"Ignominia", definicion:"Afrenta pública."},
    {palabra:"Afrenta", definicion:"Vergüenza, Deshonor."},
    {palabra:"Telúrico", definicion:"Pertieneciente o relativo a la tierra como planeta."},
    {palabra:"Derogar", definicion:"Abolir una norma."},
    {palabra:"Marasmo", definicion:"Paralización en lo moral y en lo físico."},
    {palabra:"Cochambre", definicion:"Suciedad puerca, grasienta y de mal olor."},
    {palabra:"Latrocinio", definicion:"Acción propia de un ladrón."},
    {palabra:"Idiosincrasia", definicion:"Rasgos de una colectividad."},
    {palabra:"Heurística", definicion:"Busqueda e investigación. / Solución de problemas por tanteo."},
    {palabra:"Acracia", definicion:"Concepción que niega cualquier autoridad."},
    {palabra:"Acicate", definicion:"Incentivo"},
    {palabra:"Aforar", definicion:"Dar o tomar a foro alguna heredad."},
    {palabra:"Paradigma", definicion:"Ejemplo."},
    {palabra:"Demótico", definicion:"Variedad hablada de la lengua griega."},
    {palabra:"Endógeno", definicion:"Originado o generado dentro de una cosa. Ej: Causas endógenas de su problema psicológico"},
    {palabra:"Exógeno", definicion:"Originado o generado en el exterior de una cosa. Ej: Causas exógenas de su problema psicológico"},
    {palabra:"Anacrónico", definicion:"Error de suponer un hecho en un tiempo erróneo."},
    {palabra:"Oriundo", definicion:"Originario de un lugar"},
    {palabra:"Plúmbeo", definicion:"Pesado, aburrido"},
    {palabra:"Vulgo", definicion:"Gente común y vulgar sin conocimiento"},
    {palabra:"Onanimso", definicion:"Masturbación."},
    {palabra:"Fruslería", definicion:"De poco valor."},
    {palabra:"Circunspecto", definicion:"Prudente, decoroso"},
    {palabra:"Enjundia", definicion:"Parte más sustanciosa e importante de algo no material. / Valor, fuerza."},
    {palabra:"Vacuo", definicion:"Vacío, Falto de contenido."},
    {palabra:"Pleonasmo", definicion:"Redundancia de palabras."},
    {palabra:"Incólume", definicion:"Sano, sin lesión."},
    {palabra:"Jingoismo", definicion:"Patriotismo, Agresión a otras naciones."},
    {palabra:"Perendeca", definicion:"Prostituta."},
    {palabra:"Lacerante", definicion:"Que provoca sufrimiento."},
    {palabra:"Mesalina", definicion:"Prostituta, Emperatriz romana promicua y lujuriosa, cruel."},
    {palabra:"Meretriz", definicion:"Prostituta."},
    {palabra:"Ínclito", definicion:"Noble, culto, sobresaliente."},
    {palabra:"Anodino", definicion:"Insignificante."},
    {palabra:"Apostatar", definicion:"Abandonar un bautismo o doctrina."},
    {palabra:"Voluptuosidad", definicion:"Complacencia a los placeres sensuales."},
    {palabra:"Hedonismo", definicion:"Doctrina que tiene como fin supremo de la vida el placer."},
    {palabra:"Impúdico", definicion:"Sin pudor."},
    {palabra:"Cosificar", definicion:"Reducir a la condición de cosa lo que no es."},
    {palabra:"Miscible", definicion:"Mezclable."},
    {palabra:"elucidación", definicion:"Explicación."},
    {palabra:"Inopia", definicion:"Pobreza, ignorancia, escasez intelectual."},
    {palabra:"Abulia", definicion:"Falta de voluntad."},
    {palabra:"Tautología", definicion:"Repetición inutil y viciosa"},
    {palabra:"Apócope", definicion:"Supresión de algún sonido al final de un vocablo. Ej: Poli de policía."},
    {palabra:"Agnosticismo", definicion:"Doctrina que declara innaccesible el entendimiento de lo divino y lo que transciende a la experiencia."},
    {palabra:"Eclecticismo", definicion:"Posición intermedia / Conciliar diferentes doctrinas."},
    {palabra:"Equidad", definicion:"Moderación."},
    {palabra:"Filántropo", definicion:"Amante de sus semejantes."},
    {palabra:"Etnocentrismo", definicion:"Superposición de lo valores y virtudes del propio pueblo sobre el resto."},
    {palabra:"Empirismo", definicion:"Basado en la experiencia."},
    {palabra:"Concupiscencia", definicion:"Deseo de bienes y placeres deshonestos."},
    {palabra:"Ponderar", definicion:"Encarecer"},
    {palabra:"Facción", definicion:"Grupo de personas unidas por ideas o intereses comunes dentro de una agrupación o colectividad. / Acción de guerra. / Gente amotinada."},
    {palabra:"Otrora", definicion:"En otro tiempo, en un tiempo pasado."},
    {palabra:"Nefando", definicion:"Indigno, torpe."},
    {palabra:"Fáctico", definicion:"Basado en hechos."},
    {palabra:"Exégesis", definicion:"Interpretación."},
    {palabra:"Escisión", definicion:"Rompimiento."},
    {palabra:"Retórica", definicion:"Arte del bien decir."},
    {palabra:"Metonimia", definicion:"Designar a algo con el nombre de otra cosa. Ej: Amigo -> Killo"},
    {palabra:"Perfidia", definicion:"Deslealtad, Traición."},
    {palabra:"Diatriba", definicion:"Discuros violento e injurioso contra alguien o algo."},
    {palabra:"Foribundo", definicion:"Colérico, furor, entusiasta o partidario."},
    {palabra:"Chovinismo", definicion:"Patriotismo fanático."},
    {palabra:"Funesto", definicion:"Triste y desgraciado."},
    {palabra:"Lícito", definicion:"Justo, con razón."},
    {palabra:"Agiotista", definicion:"Especulador, usurero."},
    {palabra:"Envilecer", definicion:"Hacer vil, hacer despreciable."},
    {palabra:"Probidad", definicion:"Honradez."},
    {palabra:"Probo", definicion:"Honrado."},
    {palabra:"Bogar", definicion:"Conducir remando."},
    {palabra:"Hidropésia", definicion:"Derrame o acumulación de líquido seroso."},
    {palabra:"Abjurar", definicion:"Renegar."},
    {palabra:"Exigua", definicion:"Insuficiente, escaso."},
    {palabra:"Dicción", definicion:"Palabra."},
    {palabra:"Cimero", definicion:"Que está en la parte superior."},
    {palabra:"Preterida", definicion:"Omitida."},
    {palabra:"Inepcia", definicion:"Ineptitud, necio."},
    {palabra:"Prospectivo", definicion:"Que se refiere al futuro."},
    {palabra:"Homónima", definicion:"Que lleva un mismo nombre."},
    {palabra:"Ortodoxia", definicion:"Conformidad con doctrinas dominantes o prácticas admitidas."},
    {palabra:"Panóptico", definicion:"Que toda su parte interior se ve desde el interior."},
    {palabra:"Oxímoron", definicion:"Uso de dos conceptos opuestos. Ej: Un instante eterno."},
    {palabra:"Denostar", definicion:"Injuriar gravemente."},
    {palabra:"Ignoto", definicion:"No conocido."},
    {palabra:"Timorato", definicion:"Tímido, indeciso."},
    {palabra:"Veleidoso", definicion:"Inconstante, mudable."},
    {palabra:"Cinismo", definicion:"Obscenidad descarada, desvergüenza en mentir."},
    {palabra:"Epílogo", definicion:"Recapitulación de los dicho en un discurso."},
    {palabra:"Semántico", definicion:"Significación de palabras."},
    {palabra:"Antonomasia", definicion:"Justificación de nombre apelativo a cosa o persona."},
    {palabra:"Apelativo", definicion:"Que apellida o califica."},
    {palabra:"Calificar", definicion:"Determinar algo."},
    {palabra:"Plétora", definicion:"Gran abundancia de algo."},
    {palabra:"Inenarrable", definicion:"Inexplicable con palabras."},
    {palabra:"Soslayo", definicion:"Pasar por alto."},
    {palabra:"Sinóptico", definicion:"Característico de la sinopsis. Resumido."},
    {palabra:"Apócrifo", definicion:"Dicho de un libro de un autor sagrado que no está en la Biblia. / Fabuloso. / Supuesto o fingido."},
    {palabra:"Sine qua non", definicion:"Condición sin la cual..."},
    {palabra:"Gnosticismo", definicion:"Doctrina que mezcla creencias judías y orientales."},
    {palabra:"Eufemismo", definicion:"Manifestación suave y decorosa de una malsonante y dura. Ej: Sexo = Hacer el amor."},
    {palabra:"Parangonar", definicion:"Hacer comparación de una cosa con otra."},
    {palabra:"Oprobio", definicion:"Ignominia, Afrenta, Deshonra."},
    {palabra:"Cerrilismo", definicion:"Cualidad de cerril."},
    {palabra:"Cerril", definicion:"Tosco, grosero. / Terreno áspero y escabroso."},
    {palabra:"Antisemita", definicion:"Enemigo de la raza hebréa ( israelitas y judios )."},
    {palabra:"Semita", definicion:"Dicho de una persona: Que pertenece a alguno de los pueblos que integran la familia formada por los árabes, los hebreos y otros."},
    {palabra:"Sucinta", definicion:"Breve. / Recogido o ceñido por abajo."},
    {palabra:"Exornar", definicion:"Adornar, embellecer, hermosear."},
    {palabra:"Epifenómeno", definicion:"Fenómeno que acompaña al fenómeno principal pero no tiene influencia sobre él."},
    {palabra:"Empresario", definicion:"Que realiza una obra."},
    {palabra:"Misógeno", definicion:"Que odia a las mujeres."},
    {palabra:"Disensión", definicion:"Contradicción en los pareceres. / Contienda, riña."},
    {palabra:"Epigrama", definicion:"Inscripción en piedra. / Pensamiento breve. / Composición poética breve."},
    {palabra:"Escribano", definicion:"Maestro del escribir."},
    {palabra:"Patíbulo", definicion:"Lugar donde se ejecuta la pena de muerte."},
    {palabra:"Fútil", definicion:"De poco aprecio o importancia."},
    {palabra:"Efebo", definicion:"Adolescente de belleza afeminada."},
    {palabra:"Teutón", definicion:"Alemán."},
    {palabra:"Códice", definicion:"Libro anterior a la imprenta."},
    {palabra:"Arenga", definicion:"Discurso para enardecer los ánimos."},
    {palabra:"Contractual", definicion:"Procedente del contrato o derivado de él."},
    {palabra:"Anquilosar", definicion:"Paralizar su evolución."},
    {palabra:"Inextricable", definicion:"Muy enredado y confuso."},
    {palabra:"Cohonestar", definicion:"Dar apariencia de justa o razonable a una acción que no lo es. / Hacer compatibles dos o más cualidades, actitudes o acciones."},
    {palabra:"Trapacero", definicion:"Que con astucias, falsedades y mentiras procura engañar a alguien en un asunto."},
    {palabra:"Molicie", definicion:"Blandura de las cosas al tacto. / Abandono invencible al placer de los sentidos o a una grata pereza."},
    {palabra:"Prez", definicion:"Honor, estima o consideración que se adquiere o gana con una acción gloriosa."},
    {palabra:"Consciencia", definicion:"Similar a conciencia pero no difiere el bien y el mal ( moral )."},
    {palabra:"Asepsia", definicion:"Estado libre de infección."},
    {palabra:"Ostracismo", definicion:"Destierro político."},
    {palabra:"Tácito", definicion:"Callado, silencioso. / Que no se entiende, se supone."},
    {palabra:"Falaz", definicion:"Embustero, Falso."},
    {palabra:"Conspicuo", definicion:"Notable, ilustre, sobresaliente."},
    {palabra:"Espurio", definicion:"Bastardo."},
    {palabra:"Senectud", definicion:"Periodo de la vida que sigue a la madurez."},
    {palabra:"Laxo", definicion:"De moral relajada, libre o poco sana."},
    {palabra:"Contradicción", definicion:"Antítesis, paradoja, discordancia, antilogía."},
    {palabra:"Inefable", definicion:"Que no se puede expresar con palabras."},
    {palabra:"Andrógino", definicion:"Rasgos que no son de su sexo."},
    {palabra:"Pagano", definicion:"Infiel, no bautizado. / Idólatra de los antiguos griegos y romanos."},
    {palabra:"Embridar", definicion:"Poner bridas. / Someter, sujetar."},
    {palabra:"Tórpida", definicion:"Que reacciona con torpeza."},
    {palabra:"Empozoñar", definicion:"Echar a perder. Dañar."},
    {palabra:"Escepticismo", definicion:"Doctrina que afirma que la verdad no existe. / Desconfianza, duda."},
    {palabra:"Paráfrasis", definicion:"Explicación o interpretación amplificada de un texto para ilustralo o hacerlo más claro."},
    {palabra:"Adujar", definicion:"Recogerse para comodarse en poco espacio."},
    {palabra:"Libar", definicion:"Chupar suavemente el jugo de una cosa."},
    {palabra:"Virtud", definicion:"Disposición del alma para con la ley moral."},
    {palabra:"Ardid", definicion:"Medio empleado para el logro de algo mañosamente. / Mañoso, astuto, sagaz."},
    {palabra:"Prólijo", definicion:"Que pone esmero en los detalles. / Largo, dilatado, en exceso. / Cuidadoso, esmerado. / Impertinente, molesto."},
    {palabra:"Ambivalencia", definicion:"Condición que se presta a dos interpretaciones opuestas. / Estado de ánimo donde coexisten dos emociones o sentimientos opuestos."},
    {palabra:"Escarnio", definicion:"Burla tenaz."},
    {palabra:"Labriego", definicion:"Labrador rustico."},
    {palabra:"Ingente", definicion:"Muy grande."},
    {palabra:"Acopio", definicion:"Reunir, recolectar algo."},
    {palabra:"Corolario", definicion:"Proposición que no necesita prueba alguna."},
    {palabra:"Escatológico", definicion:"Perteneciente a las postrimerías de ultratumba. / Relativo a los excrementos y suciedades."},
    {palabra:"Postrimerías", definicion:"Periodo último de la duración de algo."},
    {palabra:"Aporía", definicion:"Enunciado que contiene una inviabilidad de orden racional."},
    {palabra:"Vilipendiar", definicion:"Despreciar."},
    {palabra:"Disquisición", definicion:"Exámen riguroso."},
    {palabra:"Vituperar", definicion:"Censurar."},
    {palabra:"Tetralogías", definicion:"Conjunto de 4 obras literarias o musicales."},
    {palabra:"Inconexo", definicion:"Falto de conexión."},
    {palabra:"Opúsculo", definicion:"Obra de poca extensión."},
    {palabra:"Autarquía", definicion:"Dominio de sí mismo. / Política de un Estado que se bas con sus propios recursos."},
    {palabra:"Asechanza", definicion:"Engaño o artificio para hacer daño a alguien."},
    {palabra:"Disertar", definicion:"Razonar, discurrir detenidamente sobre alguna materia."},
    {palabra:"Anagnórisis", definicion:"Recurso narrativo, consiste en el descubrimiento por parte de un personaje de datos de su identidad."},
    {palabra:"Areté", definicion:"Excelencia."},
    {palabra:"Sátrapa", definicion:"Hombre sagaz que sabe gobernar con astucia, o que gobierna despóticamente."},
    {palabra:"Irisado", definicion:"Que brilla o destella con colores semejante al iris."},
    {palabra:"Ubicuo", definicion:"Dios que esta en todas partes. / Persona que lo quiere ver todo y esta en continuo movimiento."},
    {palabra:"Soliviantar", definicion:"Inquietar o alterar a alguien."},
    {palabra:"Leguleyo", definicion:"Persona que aplica el derecho sin rigor."},
    {palabra:"Presuntuoso", definicion:"Lleno de orgullo y presunción. / Que se hace pasar por muy elegante o lujoso."},
    {palabra:"Dislate", definicion:"Disparate."},
    {palabra:"Ignaro", definicion:"Que no tiene noticias de las cosas."},
    {palabra:"Adocenar", definicion:"Hacer mediocre."},
    {palabra:"Apátrida", definicion:"Que carece de nacionalidad."},
    {palabra:"Arracachá", definicion:"Sandez."},
    {palabra:"Inanidad", definicion:"Vacuidad, futilidad."},
    {palabra:"Metempsicosis", definicion:"Creencia de transmigración de las almas."},
    {palabra:"Orfismo", definicion:"Creencia religiosa, el cuerpo como carcel del alma. Metempsicosis."},
    {palabra:"Bifronte", definicion:"De dos frentes, de dos caras."},
    {palabra:"Insondable", definicion:"Que no se puede hayar su fondo con la sonda."},
    {palabra:"Pretérito", definicion:"Pasado, sucedido."},
    {palabra:"Cosmogonía", definicion:"Teoría científica de origen y evolución del universo y el mundo."},
    {palabra:"Cosmología", definicion:"Parte de la astronomía que trata las leyes generales del origne y evolución del universo. / Conocimiento filosófico leyes que rigen el mundo físico."},
    {palabra:"Monismo", definicion:"Reducir seres y fenómenos a 1 sustancia única de la que todos derivan."},
    {palabra:"Abolengo", definicion:"Ascendencia de abuelos o antepasados ilustres."},
    {palabra:"En ciernes", definicion:"En flor, estar en sus principios."},
    {palabra:"Ínfula", definicion:"Cada una de las dos cintas de la mitra episcopal."},
    {palabra:"Episcooal", definicion:"Perteneciente o relativo al obispo."},
    {palabra:"Apotegma", definicion:"Dicho breve de alguien ilustre."},
    {palabra:"Cogitativo", definicion:"Que tiene la facultad de pensar."},
    {palabra:"Lacónico", definicion:"Breve, conciso."},
    {palabra:"Necedad", definicion:"Calidad de necio."},
    {palabra:"Dispendio", definicion:"Gasto excesivo e innecesario."},
    {palabra:"Adefesio", definicion:"Despropósito, disparate. / Traje rídiculo. / Persona ridícula."},
    {palabra:"Asertivo", definicion:"Afirmativo, que tiene ideas positivas."},
    {palabra:"Contingente", definicion:"Que puede o no puede suceder."},
    {palabra:"Anatema", definicion:"Maldición, excomunión."},
    {palabra:"Licitar", definicion:"Subastar."},
    {palabra:"Ingénito", definicion:"No engendrado."},
    {palabra:"Oftalmía", definicion:"Inflamación de los ojos."},
    {palabra:"Palinodia", definicion:"Retractación pública."},
    {palabra:"Homónimo", definicion:"2 cosas con el mismo nombre."},
    {palabra:"Verosimil", definicion:"Creíble por no mostrar falsedad."},
    {palabra:"Prócer", definicion:"Eminente, elevado, alto."},
    {palabra:"Meliflua", definicion:"que tiene miel. / dulce, suave, tierno, delicado."},
    {palabra:"Numen", definicion:"Deidad dotada de poder. / Dioses de la mitología clásica. / Inspiración del artista."},
    {palabra:"Denuedo", definicion:"Brío, esfuerzo, valor, intrepidez."},
    {palabra:"Panoplia", definicion:"armadura completa con todas las piezas. / conjunto amplio y variado de elementos del mismo carácter. (una panoplia de ideas)."},
    {palabra:"Olocracia", definicion:"Gobierno de la plebe o la muchedumbre."},
    {palabra:"Panacea", definicion:"Remedio que cura cualquier mal."},
    {palabra:"Paroxismo", definicion:"Exaltación extrema de los afectos y pasiones."},
    {palabra:"Adlátere", definicion:"Persona subordinada a otra."},
    {palabra:"Dimanar", definicion:"Manar. / Proceder. provenir y tener origen una cosa de otra."},
    {palabra:"Avezar", definicion:"Acostumbrar."},
    {palabra:"Polímata", definicion:"Persona que sabe de muchos campos. ( Da Vinci, Aristóteles, etc )"},
    {palabra:"Ucronía", definicion:"Genereo literario que da por supuesto acontecimientos no sucedidos. ( Republicanos ganaron, Dinosaurios no se extinguieron, etc. )"},
    {palabra:"Perentoria", definicion:"Definitivo, Último plazo que se concede de un asunto. / Concluyente, determinante. / Urgente"},
    {palabra:"Efeméride", definicion:"Acontecimiento importante que se recuerda en cualquier aniversario de él."},
    {palabra:"Soliloquio", definicion:"Habla a solas."},
    {palabra:"Ineluctable", definicion:"Cosa que no puede contradecirse."},
    {palabra:"Frugalidad", definicion:"Templanza."},
    {palabra:"Casquivana", definicion:"Alegre de cascos. (cachonda)"},
    {palabra:"Providencia", definicion:"Disposición anticipada que conduce a un fín"},
    {palabra:"Áulicos", definicion:"Relativo de un palacio."},
    {palabra:"Raigambre", definicion:"Conjunto de raíces unidas entre sí. / Antecedentes, hábitos que ligan a alguien a un sitio."},
    {palabra:"Elidir", definicion:"Frustar, debilitar, desvanecer."},
    {palabra:"Elocuencia", definicion:"Facultad de hablar o escribir para deleitar y conmover."},
    {palabra:"Omnímodo", definicion:"Que lo abraza y lo comprende todo."},
    {palabra:"Cisma", definicion:"División, separación, escisión, discordia, desaveniencia."},
    {palabra:"Prosapia", definicion:"Ascendencia, linaje o generación de una persona."},
    {palabra:"Alcurnia", definicion:"Ascendencia o linaje sobre todo si es noble y antiguo."},
    {palabra:"Desafuero", definicion:"Acto violento contra la ley. / Acción contraria a las buenas costumbres o a la razón. / Privar de fuero a quien lo tenía."},
    {palabra:"Sicofante", definicion:"Impostor, calumniador."},
    {palabra:"Adusto", definicion:"Poco tratable. / Seco, severo. / Quemado, tostado."},
    {palabra:"Solecismo", definicion:"Error contra las normas de algún idioma."},
    {palabra:"Lego", definicion:"Falto de noticias o letras."},
    {palabra:"Pústula", definicion:"Vejiga inflamatoria llena de pús."},
    {palabra:"Semántica", definicion:"Significado de las palabras."},
    {palabra:"Semiótica", definicion:"Teoría de los signos."},
    {palabra:"Sine qua non", definicion:"Sin la cual no..."},
    {palabra:"Pedestre", definicion:"Vulgar, llano, inculto, bajo."},
    {palabra:"Endónimo", definicion:"Designa el hecho que un grupo de personas empela de manera regular un nombre para indeticarse. Ej: Americanos, Hélade."},
    {palabra:"Prosaico", definicion:"Adocenado, vulgar, tosco. / Práctico, útil."},
    {palabra:"Galano", definicion:"Elegante."},
    {palabra:"Heteronomia", definicion:"Ausencia de autonomía, de voluntad: que se rige por un poder externo."},
    {palabra:"Díscolo", definicion:"Desobediente."},
    {palabra:"Transigir", definicion:"Consertir lo que no es justo para acabar con una diferencia."},
    {palabra:"Incidental", definicion:"Accesorio de menor importancia."},
    {palabra:"Deferencia", definicion:"Muestra de respeto y cortesía. Adherencia con la opinión o el comportamiento por respeto hacia ella o por excesiva moderación."},
    {palabra:"Hablantín", definicion:"Que habla de lo que no debe."},
    {palabra:"Fictivo", definicion:"Que vive o existe en la ficción literaria."},
    {palabra:"Somero", definicion:"Ligero, superficial, de poca importancia."},
    {palabra:"Anacoluto", definicion:"Incosecuencia en la construcción de un discurso o frase."},
    {palabra:"Ampuloso", definicion:"Lenguaje hinchado y redundante."},
    {palabra:"Melopeya", definicion:"Arte de producir melodías."},
    {palabra:"Inverecundia", definicion:"Desvergüenza, desfachatez."},
    {palabra:"Verecundia", definicion:"Vergüenza."},
    {palabra:"Tecnolatría", definicion:"Desorden de la técnica y veneración incodnicional. / Deificacion de la tecnología."},
    {palabra:"Nefario", definicion:"Sumamente malvado, impío e indigno del trato humano."},
    {palabra:"Ortofonía", definicion:"Correción de los defectos de la voz y de la pronunciación."},
    {palabra:"Agnición", definicion:"Anagnórisis."},
    {palabra:"Deprecar", definicion:"Rogar, pedir, suplica con eficacia o insistencia."},
    {palabra:"Paralogismo", definicion:"Razonamiento falso."},
    {palabra:"Distopía", definicion:"Representación ficticia de una sociedad futura de características negativas causantes de la alineación humana."},
    {palabra:"Elegía", definicion:"Composición poética de género lírico que lamenta un acontecimiento digno de ser llorado."},
    {palabra:"Oneroso", definicion:"Pesado, molesto, gravoso."},
    {palabra:"Pesadumbre", definicion:"Molestia, desazón, padecimiento físico o moral."},
    {palabra:"Altanero", definicion:"Altivo, soberbio."},
    {palabra:"Arrostar", definicion:"Hacer cara, resistir sin muestras de debilidad."},
    {palabra:"Impasible", definicion:"Que no padece."},
    {palabra:"Eximio", definicion:"Muy ilustre, excelso."},
    {palabra:"Estulticia", definicion:"Necedad, tontería."},
    {palabra:"Huero", definicion:"Vano, vacío, sin sustancia."},
    {palabra:"Encomio", definicion:"Alabanza encarecida."},
    {palabra:"Interpolar", definicion:"Poner algo entre otras cosas."},
    {palabra:"Baladí", definicion:"De poca importancia."},
    {palabra:"Alocución", definicion:"Discurso de un superior a sus secuaces."},
    {palabra:"Teleología", definicion:"Doctrinas de las causas finales."},
    {palabra:"Epígono", definicion:"Hombre que sigue las huellas de otro."},
    {palabra:"Iltericia", definicion:"Mal qeu necesitaba de grandes gastos para curarlo."},
    {palabra:"Manumisión o manumitir", definicion:"Dar libertad a un esclavo."},
    {palabra:"Lisura", definicion:"Igualdad de la superficie. / Ingenuidad, sinceridad."},
    {palabra:"Ornato", definicion:"Adorno, atavío."},
    {palabra:"Perífrasis", definicion:"Circunlocución."},
    {palabra:"Circunlocución", definicion:"Rodeo de palabras algo que se podría decir con menos."},
    {palabra:"Gozne", definicion:"Bisagra."},
    {palabra:"Istmo", definicion:"Camino de tierra que une dos islas."},
    {palabra:"Sincopar", definicion:"Abreviar, acortar. / Supresión de sonidos de una palabra. Ej: Navidad por Natividad."},
    {palabra:"Argentado", definicion:"Bañado en plata."},
    {palabra:"Probidad", definicion:"Honradez."},
    {palabra:"Aciago o infausto", definicion:"Desgraciado, infeliz."},
    {palabra:"Ufano", definicion:"Arrogante, engreido"},
    {palabra:"Altitronante", definicion:"Que truena desde lo alto."},
    {palabra:"Heraldo", definicion:"Mensajero. / Aquello que anuncia que va a suceder algo."},
    {palabra:"Sempiterno", definicion:"Que dura siempre. / Perpetuo."},
    {palabra:"Níveo", definicion:"De nieve."},
    {palabra:"Égida", definicion:"Protección, defensa."},
    {palabra:"Torva", definicion:"Remolina de lluvia o nieve."},
    {palabra:"Libelo", definicion:"Libro pequeño."},
    {palabra:"Lumpen", definicion:"Lumpemproletariado."},
    {palabra:"Lumpemproletariado", definicion:"Capa social más baja y sin conciencia de clase."},
    {palabra:"Fungible", definicion:"Que se consume con el uso."},
    {palabra:"Petimetre", definicion:"Persona que se procupa mucho de su compostrua y seguir las modas."},
    {palabra:"Indefectible", definicion:"Que no puede faltar."},
    {palabra:"Lenidad", definicion:"Blandura de exigir deberes o castigar faltas."},
    {palabra:"Improvidad", definicion:"Desprevenido, desapercibido. Falto de lo necesario."},
    {palabra:"Trapacero", definicion:"Trapero, astuto, mentiroso."},
    {palabra:"Molicie", definicion:"Abandono al placer de los sentidos y la pereza. / Blandura al tacto."},
    {palabra:"Prez", definicion:"Honor, estima, consideración."},
    {palabra:"Pendencia", definicion:"Contienda, riña."},
    {palabra:"Ubi Dubium ibi libertas", definicion:"Donde hay duda hay libertad."},
    {palabra:"Gleba", definicion:"Terrón que se levanta del arado. / Gente del pueblo bajo."},
    {palabra:"Exánime", definicion:"Sin señal de vida. / Debilitado sin aliento, desmayado."},
    {palabra:"Perínclito", definicion:"Grande heróico, inclito de sumo grado."},
    {palabra:"Posopopeya", definicion:"Atribución a las cosas inanimadas o abstractas de cualidades de seres animados, o a los seres ideales las del ser humano."},
    {palabra:"Sustantivar", definicion:"Considerar algo como sustancia."},
    {palabra:"Célere", definicion:"Pronto, rápido."},
    {palabra:"Univocar", definicion:"Convertir en una razón mismas una o más cosas."},
    {palabra:"Coyuntural", definicion:"Que depende de los factores y efectos que se den."},
    {palabra:"Contingente", definicion:"Que puede o no suceder."},
    {palabra:"Descollar", definicion:"Sobresalir, Distinguirse."},
    {palabra:"Reificación", definicion:"Cosificación."},
    {palabra:"Contricción", definicion:"Arrepentimiento de una culpa."},
    {palabra:"Lábil", definicion:"Que resbala. / Frágil. / Poco estable."},
    {palabra:"Obliterar", definicion:"Anular, tachar, borrar. / Cerrar u obstruir un conducto."},
    {palabra:"Exégeta", definicion:"Persona que interpreta o expone un texto."},
    {palabra:"Espetar", definicion:"Clavar. / Encajar, asegurar, afianzar. / Decir algo a alguien que le cause sorpresa."},
    {palabra:"Diletante", definicion:"Conocedor de las artes. / Que cultiva campos del saber."},
    {palabra:"Quinquenio", definicion:"Periodo de 5 años."},
    {palabra:"Quingentesimo", definicion:"Periodo de 500 años."},
    {palabra:"Zaherir", definicion:"Humillar o mortificar a alguien."},
    {palabra:"Exordio", definicion:"Origen o principio de algo. / Preámbulo de un razonamiento."},
    {palabra:"Volitivo", definicion:"Relativo a al voluntad."},
    {palabra:"Doltitud", definicion:"Cualidad de docto."},
    {palabra:"Extemporáneo", definicion:"Impropio del tiempo en que sucede o se hace. / Inoportuno, inconveniente."},
    {palabra:"Sinarquía", definicion:"Gobierno constituido por varios principes cada uno de los cuales administra un estado."},
    {palabra:"Aquiescencia", definicion:"Asenso, consentimiento."},
    {palabra:"Asenso", definicion:"Acción e asentir."},
    {palabra:"Execrar", definicion:"Condenar y maldecir en nombre de cosas sagradas. / Vituperar o reprobar severamente. / Aborrecer."},
    {palabra:"Baldón", definicion:"Injuria, afrenta. / Persona o cosa que supone baldón."},
    {palabra:"Plutocracia", definicion:"Situación en la que los ricos ejercen su preponderancia en el gobierno del estado. / Conjunto de ciudadanos adinerados que ejercen su influencia en el gobierno del estado."},
    {palabra:"Egregio", definicion:"Famoso, ilustre, notable, eminente."},
    {palabra:"Zafio", definicion:"Persona grosera o tosca en sus modales, o carente de tacto en su comportamiento, inculto, ordinario, cateto, cerril, vulgar."},
    {palabra:"Arrabalero", definicion:"Grosero, tosco, cerril, ordinario."},
    {palabra:"Entelequia", definicion:"Cosa irreal. / En Aristóteles: Fín u objetivo de una actividad que la completa y la perfecciona."},
    {palabra:"Nepotismo", definicion:"Preferencia que se dan a parientes para concesiones o empleos públicos."},
    {palabra:"Ergo", definicion:"Latin: Por tanto, luego, pues..."},
    {palabra:"Silogismo", definicion:"Método mediante el cual se realiza un razonamiento deductivo."},
    {palabra:"Razonamiento deductivo", definicion:"El que se usa para determinar si un hecho o idea es cierto al compararlo con una idea o hecho universal."},
    {palabra:"Inferir", definicion:"Formular perdicciones o hipótesis acerca de un tema."},
    {palabra:"Leguleyo", definicion:"Discutidor. / Persona que aplica el derecho sin rigor."},
    {palabra:"Aserción", definicion:"Afirmar, dar por cierto algo. / Proposición en que se afirma o da algo por cierto."},
    {palabra:"Ufano", definicion:"Arrogante, engreido. / Satisfecho, alegre, contento. / Que procede en la ejecución de algo."},
    {palabra:"Precepto", definicion:"Mandato que el superior hace obedecer y guardar al inferior."},
    {palabra:"Alambicado", definicion:"Sutil. / Complicado, rebuscado. / Dado con escasez y muy poco a poco."},
    {palabra:"Cratología", definicion:"Ciencia que estudia el poder."},
    {palabra:"Enjundia", definicion:"Fuerza, vigor./ Parte más sustanciosa e importante de algo no material. / constitución o cualidad connatural de una persona."},
    {palabra:"Quiescente", definicion:"Que esta quieto pudiendo tener movimiento propio."},
    {palabra:"Misantropía", definicion:"Aversión al género humano."},
    {palabra:"Abyecto", definicion:"Vil en extremo, despreciable."},
    {palabra:"Incoar", definicion:"Llevar a cabo los primeros trámites de una actuación oficial."},
    {palabra:"Felonía", definicion:"Deslealtad, traición, acción fea."},
    {palabra:"Ataraxia", definicion:"Estado de ánimo que se caracteriza por la tranquildad y la total ausencia de deseos o temores."},
    {palabra:"Estultos", definicion:"Necios, ignorantes."},
    {palabra:"Preconizar", definicion:"Encomiar, elogiar. / Apoyar algo, recomendar algo, proponer algo."},
    {palabra:"Boato", definicion:"Ostentación en el porte exterior."},
    {palabra:"Iracundo", definicion:"Que muestra ira."},
    {palabra:"Mor", definicion:"Latin: Por causa de..."},
    {palabra:"Supino", definicion:"Dicho de algo negativo. Ej: Estupidez supina."},
    {palabra:"Horrisono", definicion:"Que su sonido causa horror y espanto."},
    {palabra:"Crátera", definicion:"En Grecia y Roma donde se mezclaba el vino con agua."},
    {palabra:"Palinodia", definicion:"Retractación pública."},
    {palabra:"Malgré lui", definicion:"A pesar de..."},
    {palabra:"Solipismo", definicion:"Creencia metafísica que dice que de lo único que se puede estar seguro es de la existencia de su propia mente y que la realidad que nos rodea es incognoscible."},
    {palabra:"Eufonía", definicion:"Efecto acústico que resulta de la combinación de sonidos en uan palabra o frase."},
    {palabra:"Disgresión", definicion:"Apartarse de un relato o discurso para traar algo relacionado con él."},
    {palabra:"Escamotear", definicion:"Robar o quitar algo con agilidad y astucia."},
    {palabra:"Coyuntura", definicion:"Conjunto de circunstancias que determinan una situación."},
    {palabra:"Ciscar", definicion:"Cagar, defecar, evacuar, ensuciar."},
    {palabra:"Maniqueismo", definicion:"Doctrina que se basa en dos principios bien y mal. / Cualquier actitud que mantiene posturas extremas sin puntos intermedios."},
    {palabra:"Solaz", definicion:"Placer, entretenimiento y descanso en las actividades y trabajo."},
    {palabra:"Simiesco", definicion:"Relacionado con el simio."},
    {palabra:"Deslavazado", definicion:"Insustancial. / Que carece de unión entre sus partes o esta desordenado o mal compuesto."},
    {palabra:"Alicorta", definicion:"Que tiene alas cortas o cortadas."},
    {palabra:"Orbe", definicion:"Mundo"},
    {palabra:"Inánime", definicion:"Sin señal de vida, que no tiene alma."},
    {palabra:"Inane", definicion:"Vano, fútil, inútil."},
    {palabra:"Per se", definicion:"Latín: De por sí..."},
    {palabra:"Taxativo", definicion:"Que limita. Circunscribe. / Que no admite discusión."},
    {palabra:"Vegetar", definicion:"Vivir maquinalmente como una planta. / Llevar una vida tranquila, exenta de trabajo y cuidados."},
    {palabra:"Pogromo", definicion:"Masacre aceptada o promovida por el poder de judios u otros grupos étnicos."},
    {palabra:"Sionismo", definicion:"Aspiración de los juidos a recobrar Palestina."},
    {palabra:"Pastueño", definicion:"Dicho del tro de lidia que acude sin recelo al engaño."},
    {palabra:"Hebetar", definicion:"Enervar, debilitar, embotar."},
    {palabra:"Tetrarquía", definicion:"Dignidad de tetrarca."},
    {palabra:"Tetrarca", definicion:"Gobernador de una provincia o territorio."},
    {palabra:"Malicienta", definicion:"Flaco y descolorido."},
    {palabra:"Procacidad", definicion:"Desvergüenza, insolencia, atrevimiento."},
    {palabra:"Ufanarse", definicion:"Engreirse, Jactarse, gloriarse."},
    {palabra:"Giba", definicion:"Joroba, molestia, incomodida."},
    {palabra:"Zelote", definicion:"Persona judía rígida y vehemente de su integrismo religioso"},
    {palabra:"Atavismo", definicion:"Comportamiento que hace pervivir ideas o formas de vidas propias de los antepasados."},
    {palabra:"Coprófago", definicion:"Que ingiere excrementos."},
    {palabra:"Charnego", definicion:"Inmigrante en cataluña procedente de otra región que no habla catalán."},
    {palabra:"Estupro", definicion:"Incesto, violación."},
    {palabra:"Enervar", definicion:"Debilitar. / poner de los nervios."},
    {palabra:"Panegírico", definicion:"Sermón en alabanza a alguien."},
    {palabra:"Acólito", definicion:"Monaguillo que ayuda al sacerdote."},
    {palabra:"Impenitente", definicion:"Que se obstina en el pecado. / Que persevera en un hábito."},
    {palabra:"Aciago", definicion:"Infeliz, infausto, desgraciado."},
    {palabra:"Turba", definicion:"Muchedumbre de gente confusa y desordenada."},
    {palabra:"Mor", definicion:"Por causa de..."},
    {palabra:"Tamaño", definicion:"O grande o pequeño."},
    {palabra:"Petulancia", definicion:"Vana y exagerada presunción."},
    {palabra:"Socavar", definicion:"Debilitar en el aspecto moral. / Escarvar por debajo dejándolo en falso."},
    {palabra:"Abstruso", definicion:"De dificil compresión."},
    {palabra:"Cónclave", definicion:"Junta o congreso de gente para tratar un tema."},
    {palabra:"Ponerología", definicion:"Estudio del mal, estudio de las injusticias sociales."},
    {palabra:"Patocracia", definicion:"Gobierno de una minoría patológica que toam el control de las persona normales. (Nazis)"},
    {palabra:"Filo-", definicion:"Amigo de... ( Filofascismo )"},
    {palabra:"Intestar", definicion:"Encajar una cosa con otra. / Estar lindando una cosa con otra."},
    {palabra:"Finado", definicion:"Fallecido."},
    {palabra:"Finar", definicion:"Fallecer."},
    {palabra:"Vasallaje", definicion:"De vasallo. / Vínculo de una persona a otra"},
    {palabra:"Tísico", definicion:"Que padece tísis."},
    {palabra:"Tísis", definicion:"Tubercolusos pulmonar."},
    {palabra:"Multívoco", definicion:"Que tiene varias interpretaciones."},
    {palabra:"Rémora", definicion:"Obstáculo físico o inmaterial que dificulta un proceso. Persona que retrasa, dificulta o detiene algo."},
    {palabra:"Mefistofélico", definicion:"Diabólico, malvado, perverso."},
    {palabra:"Megalómano", definicion:"Delirio de grandeza."},
    {palabra:"Egagrópila", definicion:"Bola de alimento no digerido que regurgitan las aves con pelo, huesos y plumas."},
    {palabra:"Parafilia", definicion:"Desviación sexual."},
    {palabra:"Inguinal", definicion:"Relativo a las ingles."},
    {palabra:"Emético", definicion:"Vomitivo."},
    {palabra:"Paritario", definicion:"Dicho de una asmablea donde sus partes estan en igualdad."},
    {palabra:"Vodevil", definicion:"Comedia frívola y picante basado en intriga."},
    {palabra:"Pseudo", definicion:"Falso."},
    {palabra:"Antonimia", definicion:"Condición de antónimo."},
    {palabra:"Beligerante", definicion:"Combativo."},
    {palabra:"Barragán", definicion:"Joven soltero./ Esforzado, fuerte. / Concubina."},
    {palabra:"Anarcoide", definicion:"Cualidad de anárquico."},
    {palabra:"Metástasis", definicion:"Propagación de un foco canceroso."},
    {palabra:"Rapsoda", definicion:"Poeta."},
    {palabra:"Castuzos", definicion:"Dedicado a la política sin ética. Malgobernante."},
    {palabra:"Castrense", definicion:"Relativo del ejercito."},
    {palabra:"Procrastinar", definicion:"Diferir, aplazar."},
    {palabra:"Diferir", definicion:"Aplazar."},
    {palabra:"Asueto", definicion:"Periodo de descanso y suspensión de las actividades habituales."},
    {palabra:"Agostar", definicion:"Debilitar o consumir el vigor o cualidad de una persona."},
    {palabra:"Miccionar", definicion:"Mear, orinar."},
    {palabra:"Trashumar", definicion:"Dicho de uan persona que cambia de lugar normalmente."},
    {palabra:"Filisteo", definicion:"Persona de espíritu vulgar, de escasos conocmientos y poca sensibilidad artística y literaria."},
    {palabra:"Hollar", definicion:"Pisar dejando señal pisada. / Comprimir algo con los pies. / Humillar, abatir, despreciar."},
    {palabra:"Manflota", definicion:"Burdel."},
    {palabra:"Herpético", definicion:"Que padece herpes. / Relativo al herpes."},
    {palabra:"Conciliábulo", definicion:"Junta o reunión para tratar algo oculto."},
    {palabra:"Desdeñar", definicion:"Tratar con desdén."},
    {palabra:"Mórbido", definicion:"Que padece enfermedad o la ocasiona. / Blando, suave, delicado."},
    {palabra:"Declamar", definicion:"Hablar en público con vehemencia."},
    {palabra:"Fariseo", definicion:"Hipócrita. / De mala intención."},
    {palabra:"Hiel", definicion:"Bilis. / Amargura, disgustos, advesidad."},
    {palabra:"Farfolla", definicion:"Cosa de mucha apariencia y poca entidad."},
    {palabra:"Lupanar", definicion:"Mancebía."},
    {palabra:"Mancebía", definicion:"Prostíbulo."},
    {palabra:"Errabundo", definicion:"Que va de uan parte a otra sin asiento fijo."},
    {palabra:"Prosélito", definicion:"Incorporado a una religión."},
    {palabra:"Isonomía", definicion:"Igualdad ante la ley."},
    {palabra:"Adalid", definicion:"Punta de lanza, a quien se le sigue."},
    {palabra:"Feudo", definicion:"Contrato por el cual el soberano y grandes señores concedían en la edad media, tierras o rentas en usufructo, y quien las recibía tenía que obligadamente guardar fidelidad de vasallo y prestar servicio y obligaciones."},
    {palabra:"Usufructo", definicion:"Derecho por el cual una persona puede usar los bienes de otra y dsifrutar de sus beneficios con la obligación de conservarlos y cuidarlos como si fuera suyo. / Provecho o frutos que se obtiene de una cosa."},
    {palabra:"Endogamia", definicion:"Actitud social de rechazo a la incorporación de miembros ajenos al propio grupo o instución. / Contraer matrimonio con personas de la misma ascendencia"},
    {palabra:"Fagocitar", definicion:"Absorver o neutralizar."},
    {palabra:"Subsumir", definicion:"Considerar algo como parte de un conjunto más amplio o como caso particular sometido a un principio o norma general."},
    {palabra:"Anomia / Anomía", definicion:"Estado de desorganización social o aislamiento del individuo como consecuencia de falta de congruencia de las normas sociales. / Trastorno del lenguaje, dificultad para recordar las cosas."},
    {palabra:"Distopía", definicion:"Representación de sociedad futura negativa por la alineación humana."},
    {palabra:"Edicto", definicion:"Mandato. / Escrito que se fija en los lugares públicos de las ciudades y poblados, y en el cual se da noticia de algo para que sea notorio a todos"},
    {palabra:"Plañidero", definicion:"Lloroso, lastimero."},
    {palabra:"Aducir", definicion:"Esponer algo con razones y pruebas."},
    {palabra:"Gregario", definicion:"Que junto con otros similares siguen un dogma a pies juntillas."},
    {palabra:"Tránsfuga", definicion:"Que cambia de opinion rápido."},
    {palabra:"Ígneo", definicion:"Que tiene naturaleza de fuego."},
    {palabra:"Endémico", definicion:"Propio de determinadas localizdades y regiones."},
    {palabra:"Emolumento", definicion:"Remuneración adicional que corresponde a un empleo."},
    {palabra:"Factual", definicion:"Perteneciente a los hechos."},
    {palabra:"Hipóstasis", definicion:"Considerar lo abstracto e irreal como algo real."},
    {palabra:"Inanición", definicion:"Debilidad grande por falta de algo."},
    {palabra:"Idiocia", definicion:"De idiota."},
    {palabra:"Anejo", definicion:"Unido y dependiente de algo. / Propio, inherente."},
    {palabra:"Anagogía", definicion:"Elevación y enajenamiento del alma en al contemplación de las cosas divinas."},
    {palabra:"Adumbrar", definicion:"Sombrear ( en dibujo )."},
    {palabra:"Misandria", definicion:"Aversión a los varones."},
    {palabra:"Indolente", definicion:"Que no se afecta o conmueve."},
    {palabra:"Pandemonio", definicion:"Lugar de mucho ruido y confusión."},
    {palabra:"Ripiar", definicion:"Hacer pedazos algo."},
    {palabra:"Aseverar", definicion:"Afirmar, asegurar algo que se dice."},
    {palabra:"Sinecura", definicion:"Empleo o cargo retribuido que ocasiona poco o ningún trabajo."},
    {palabra:"Pecuniario", definicion:"Relativo al dinero en efectivo."},
    {palabra:"Momio", definicion:"Sin gordura. / Chollo. / Momía."},
    {palabra:"Fielato", definicion:"Oficio de fiel."},
    {palabra:"Sevicia", definicion:"Trato cruel. / Crueldad excesiva."},
    {palabra:"Triunvirato", definicion:"Junta de 3 personas para cualquier empresa o asunto."},
    {palabra:"Dicterio", definicion:"Dicho denigrativo que insulta y provoca."},
    {palabra:"Exhabrupto", definicion:"Salida de tono."},
    {palabra:"Pudendas", definicion:"Torpe, feo, que debe causar vergüenza. / Miembro viril."},
    {palabra:"Fenecer", definicion:"Concluir, morir, poner fin a algo."},
    {palabra:"Verbigracia", definicion:"ejemplo. / Por ejemplo."},
    {palabra:"Concitar", definicion:"Provocar o causar algo con alguna reacción. / Reunir personas o cosas."},
    {palabra:"Perorar", definicion:"Pronunciar un discuro. / Hablar en la conversación familiar como si se estuviera pronunciando un discurso."},
    {palabra:"Vicario", definicion:"Que tiene las veces, poder y facultades de otra persona o la sustituye. / Segunda superiora en algunos conventos de monjas."},
    {palabra:"Chocarrero", definicion:"Grosero, fullero."},
    {palabra:"Espetar", definicion:"Decir a alguien de palabra o por escrito algo, causándole sorpresa o molestia. / Ponerse tieso, afectando gravedad y majestad. / Encajarse, asegurarse."},
    {palabra:"Atávico", definicion:"Que es arcaico o característico del pasado."},
    {palabra:"Colegir", definicion:"Juntar, inferir, sacar una consecuencia de otra cosa."},
    {palabra:"Inferir", definicion:"Sacar consecuencia de una cosa."},
    {palabra:"Sursum corda", definicion:"Latin: Arriba los corazones."},
    {palabra:"Incidental", definicion:"Que incide. / Que tiene poca importancia respecto a otra."},
    {palabra:"Colacionar", definicion:"Cotejar, colación."},
    {palabra:"Cotejar", definicion:"Confrontar algo con otra u otras cosas, o compararlas teniéndolas a la vista."},
    {palabra:"Circunciso", definicion:"Pesona circuncidada. / Moro, judio."},
    {palabra:"Litigio", definicion:"Pleito, altercado, juicio. / Disputa, contienda."},
    {palabra:"Genuflexión", definicion:"Acción y efecto de doblar la rodilla, bajándola hacia el suelo, ordinariamente en señal de reverencia."},
    {palabra:"Faccioso", definicion:"Inquieto, revoltoso, perturbador de la quietud pública."},
    {palabra:"Conflagración", definicion:"Perturbación repentina y violenta de pueblos o naciones. / Incendio grande."},
    {palabra:"Agostar", definicion:"Consumir, debilitar, o destruir las cualidades físicas o morales de alguien."},
    {palabra:"Interpelar", definicion:"Requerir, compeler, preguntar a alguien. / Implorar a alguien auxilio."},
    {palabra:"Panem et circenses", definicion:"Latin: pan y circo."},
    {palabra:"Meconio", definicion:"Primer excremento de los niños recién nacidos. Jugo que se saca de las cabezas de las adormideras en farmacia."},
    {palabra:"Deglutir", definicion:"Tragar los alimentos, hacerlos pasar de la boca al estómago."},
    {palabra:"Idus", definicion:"En el antiguo cómputo romano y en el eclesiástico, el día 15 de marzo, mayo, julio y octubre, y el 13 de los demás meses."},
    {palabra:"Coyunda", definicion:"Correa fuert y ancha. / Unión conyugal. / Sujección, dominio. / Látigo. / Pene."},
    {palabra:"Hespérides", definicion:"Mit. Griega: Eran mélides ( ninfas de árboles frutales ) que cuidaban un maravillosos jardín en un lejano rincón de occidentes. Estrabrón entre otros lo situan en Tartessos ( sur oeste de la península ibérica )"},
    {palabra:"Prea", definicion:"Cosa prendida, tomada o cogida."},
    {palabra:"Aqueo", definicion:"Natural de Acaya, región griega del norte del Peloponeso, o de la Grecia antigua."},
    {palabra:"Espolear", definicion:"Picar con la espuela al caballo. / Avivar, incitar, estimular a alguien para que haga algo."},
    {palabra:"Prorratear", definicion:"Repartir una cantidad proporcionalmente."},
    {palabra:"Erario", definicion:"Hacienda. / Contribuyente, tributario."},
    {palabra:"Arrostrar", definicion:"Hacer cara, resisitir sin cobardía calamidades o peligros."},
    {palabra:"Opulencia", definicion:"Riqueza, abundancia de bienes. / Sobreabundancia de algo."},
    {palabra:"Ánaade", definicion:"Pato."},
    {palabra:"Soporífero", definicion:"Que mueve al sueño."},
    {palabra:"Caro a Ares", definicion:"Querido por Ares."},
    {palabra:"Blasonar ", definicion:"Hacer ostentación de algo."},
    {palabra:"Envés", definicion:"Cara opuesta de una hoja."},
    {palabra:"Entrambos", definicion:"Ambos, los dos."},
    {palabra:"Chalaneo", definicion:"Trato o negocio conseguido con la destreza propia e un chalán."},
    {palabra:"Chalán", definicion:"Estafador."},
    {palabra:"Vicario", definicion:"Que ayuda o sustituye en las funciones."},
    {palabra:"Venial", definicion:"Que se opone a la ley pero es fácil de perdonar."},
    {palabra:"Protervo", definicion:"Que se obstina en la maldad. (tiene un espíritu protervo)"},
    {palabra:"Cíngulo", definicion:"Cordón, cinta, cinturón."},
    {palabra:"Fúlgida", definicion:"Fulgurante."},
    {palabra:"Artero", definicion:"Disimulado, astuto, marrullero, cuco, malicioso, diestro."},
    {palabra:"Lid", definicion:"Batalla, combate, pelea, discusión, disputa."},
    {palabra:"Impeler", definicion:"Empujar, arrojar, propulsar, impulsar, estimular, incitar."},
    {palabra:"Céfiro", definicion:"Aura, brisa, aire."},
    {palabra:"Indómito", definicion:"Indomable, indócil."},
    {palabra:"Cerviz", definicion:"Nuca, cogote."},
    {palabra:"Liza", definicion:"Plaza, campo, arena. / Combate, pelea, lid, competición."},
    {palabra:"Enhiesta", definicion:"Que esta verticalmente derecho."},
    {palabra:"Solípedos", definicion:"De un sólo dedo."},
    {palabra:"Ijada", definicion:"Cavidad entre costillas y caderas."},
    {palabra:"Refulgente", definicion:"Que emite brillo o fulgor."},
    {palabra:"Crines", definicion:"Pelo del caballor ( cuello y cola )"},
    {palabra:"Asir", definicion:"Tomar o agarrar con las manos."},
    {palabra:"Peplo", definicion:"Ropa de griega."},
    {palabra:"Icor", definicion:"Serosidad fétida que rezuman ciertas úlceras malignas."},
    {palabra:"Diligente", definicion:"Que pone interés, esmero, eficacia y rápidez en las cosas."},
    {palabra:"Cipris", definicion:"Afrodita."},
    {palabra:"Acerbo", definicion:"Áspero de sabor y olor. / Cruel muy duro."},
    {palabra:"Himeneo", definicion:"Dios del matrimonio."},
    {palabra:"Apocado", definicion:"Con timidez, humildad o vergüenza excesiva."},
    {palabra:"Tremolar", definicion:"Ondear bandera."},
    {palabra:"Oblongo", definicion:"Más alto que ancho."},
    {palabra:"Orondo", definicion:"Barrigudo, grueso, gordo, hinchando. / Dicho de una vasija de mucha concavidad."},
    {palabra:"Cotejar", definicion:"Comparar una cosa con otra."},
    {palabra:"Colación", definicion:"Cotejo que se hace de una cosa con otra. / Conferencia o conversación que tenían los antiguos monjes sobre cosas espirituales."},
    {palabra:"Refacción", definicion:"Compostura o reparación de lo estropeado. / Tentempié, restauración..."},
    {palabra:"Colegiar", definicion:"Dicho de los individuos de una misma profesión o clase: Reunirse en colegio."},
    {palabra:"Colegio", definicion:"Sociedad o reunión de personas de una misma profesión. Ej: colegio de abogados, de médicos..."},
    {palabra:"Talasocracia", definicion:"Dominio de los mares, es un concepto geoestratégico que señala al estado cuyos dominios son principalmente marítimos."},
    {palabra:"Inerme", definicion:"Que está desprovisto de medios o armas para defenderse."},
    {palabra:"Sofisma", definicion:"Razón o argumento falso con apariencia de verdad."},
    {palabra:"Dote", definicion:"Conjunto de bienes y derechos aportados por la mujer al matrimonio, que tiene como finalidad atender al levantamiento de las cargas comunes y que le deberá ser devuelto una vez disuelto aquel"},
    {palabra:"Prebenda", definicion:"Oficio, empleo o ministerio lucrativo y poco trabajoso."},
    {palabra:"Omnívoro", definicion:"Dicho de un animal: Que se alimenta de toda clase de sustancias orgánicas."},
    {palabra:"Pusilánime", definicion:"Falto de valor y ánimo para tomar decisiones o afrontar situaciones comprometidas."},
    {palabra:"Verspertino", definicion:"Perteneciente o relativo a la tarde."},
    {palabra:"Fiduciario", definicion:"Dicho de un negocio o de un contrato: Basado principalmente en la confianza entre las partes. / Persona que actúa en interés de otra sin hacerlo público."},
    {palabra:"Auscultar", definicion:"Aplicar el oído a la pared torácica o abdominal, con instrumentos adecuados. / Sondear el pensamiento de otras personas, el estado de un negocio, la disposición ajena ante un asunto."},
    {palabra:"Delicuescente", definicion:"Evanescente, sin vigor, decadente."},
    {palabra:"Apiolar", definicion:"Atar los pies de un animal muerto en la caza. / Prender. / Matar a alguien."},
    {palabra:"Claudicar", definicion:"Acabar por ceder a presión o tentación."},
    {palabra:"Hemiplejía", definicion:"Parálisis de todo el lado de un cuerpo."},
    {palabra:"Semial", definicion:"Perteneciente o relativo al semen. / Perteneciente o relativo a la semilla. / Fecundo (fértil)."},
    {palabra:"Constructo", definicion:"Construcción teórica para entender un problema determinado."},
    {palabra:"Balcanización", definicion:"División generalmente violenta y artificial por potencias extraregionales de los territorios de los paises que integran una unión."},
    {palabra:"Fuero", definicion:"Conjunto de privilegios o exenciones jurídicas de las que goza un territorio o un persona."},
    {palabra:"Conmensurar", definicion:"Medir con igual o debida proporción distintas cosas."},
    {palabra:"Concomitante", definicion:"Que aparece o actúa conjuntamente con otra cosa."},
    {palabra:"Subvenir", definicion:"Acudir al auxilio de una persona o casa. / Pagar el total de los gastos que ocasione cierta cosa."},
    {palabra:"Exonerar", definicion:"Aliviar de una carga u obligación. / Separar, privar o destituir a alguien de un empleo."},
    {palabra:"Coercitivo", definicion:"Que sirve para forzar la voluntad o la conducta de alguien. / Represivo, inhibitorio."},
    {palabra:"Diaconía", definicion:"Distrito y término en que antiguamente estaban divididas las iglesias para el socorro de los pobres, al cuidado de un diácono."},
    {palabra:"Edicto", definicion:"Mandato, decreto publicado con autoridad del príncipe o del magistrado."},
    {palabra:"Doxografía", definicion:"rama de la literatura que comprende aquellas obras dedicadas a recoger los puntos de vista de filósofos y científicos del pasado sobre filosofía, ciencia y otras materias."},
    {palabra:"Doxa", definicion:"Concepto utilizado por Parménides. Según Platón se trata de un conocimiento fenoménico y en consecuencia engañoso. Conocimiento sensible, de opinión. Platón lo confrontaba al conocimiento científico ( Episteme )."},
    {palabra:"Pistis", definicion:"Era la personificación de la buena fe, la confianza y fiabilidad."},
    {palabra:"Fenómeno", definicion:"Lo que se puede percibir con los sentidos. Es el aspecto que las cosas ofrecen ante nuestros sentidos; es decir, el primer contacto que tenemos con las cosas, lo que denominamos experiencia"},
    {palabra:"Hombre de Estado", definicion:"El de actitud reconocida para dirigir acertadamente los negocios políticos de una nación."},
    {palabra:"Extravagante", definicion:"Que se hace o dice fuera del orden o común modo de obrar. / Raro, extraño, desacostumbrado, excesivamente peculiar u original."},
    {palabra:"Diezmo", definicion:"Derecho del 10 % del valor de ciertas mercaderías, especialmente el que se pagaba al rey."},
    {palabra:"Abad", definicion:"Superior de un monasterio perteneciente a determinadas órdenes religiosas cristianas con el título de abadía."},
    {palabra:"Flatus vocis", definicion:"Un nombre, palabra o sonido sin mera correspondencia objetiva con el mundo real. Sin valor, algo insignificante y carente de sentido."},
    {palabra:"Jerigonza", definicion:"Lenguaje especial de algunos gremios. / Lenguaje de mal gusto, complicado y difícil de entender. / Acción extraña y ridícula."},
    {palabra:"Sistémico", definicion:"Perteneciente o relativo a la totalidad de un sistema; general, por oposición a local. / Perteneciente o relativo a un organismo en su conjunto."},
    {palabra:"Corifeo", definicion:"Persona que es seguida por otras en una opinión, una ideología o un partido."},
    {palabra:"Cainita", definicion:"Perteneciente o relativo a Caín. / Dicho de un sentimiento o de una actitud de rechazo: Que se dirige contra familiares o amigos."},
    {palabra:"Fratricida", definicion:"Persona que mata a su hermano."},
    {palabra:"Demiurgo", definicion:"Artífice o alma universal que es principio ordenador de los elementos preexistentes."},
    {palabra:"Inicuo", definicion:"Que no tiene equidad, que no es justo. / Que es malvado."},
    {palabra:"Iniquidad", definicion:"Injusticia o gran maldad en el modo de obrar."},
    {palabra:"Celada", definicion:"Pieza de la armadura para cubrir y proteger la cabeza."},
    {palabra:"Ladino", definicion:"Que actúa con astucia y disimulo para conseguir lo que se propone."},
    {palabra:"Sustancial", definicion:"Relativo a la sustancia de un asunto. / Lo importante o esencial."},
    {palabra:"Atómico", definicion:"Relativo al átomo, parte indivisible."},
    {palabra:"Insustancial", definicion:"Carente de sustancia o interés, o muy escaso de ellos."},
    {palabra:"Nuclear", definicion:"Pertenciente al núcleo, parte central de algo."},
    {palabra:"Revocar", definicion:"Dejar sin efecto una concesión, un mandato o una resolución. / Apartar, retraer, disuadir a alguien de un designio."},
    {palabra:"Semítico", definicion:"Relativo a los pueblos que se establecieron en Mesopotamia y el Próximo Oriente con anterioridad al primer milenio antes de Cristo y que tenían lenguas con un origen común."},
    {palabra:"Capelo", definicion:"Dignidad del cardenal."},
    {palabra:"Atopia", definicion:"Reacción anormal de hipersensibilidad frente a diversos alérgenos."},
    {palabra:"Sui generis", definicion:"De su propio género o especie."},
    {palabra:"Mónada", definicion:"Cada una de las sustancias indivisibles, pero de naturaleza distinta, que componen el universo."},
    {palabra:"Hermenéutica", definicion:"Técnica o método de interpretación de textos."},
    {palabra:"Impudicia", definicion:"Falta de recato y pudor."},
    {palabra:"Introspección", definicion:"Mirada interior que se dirige a los propios actos o estados de ánimo."},
    {palabra:"Beldad", definicion:"Belleza o hermosura de mujer. / Mujer notable por su hermosura."},
    {palabra:"Pedes in terra ad sidera visus", definicion:"Latín: Los pies en la tierra, la mirada en el cielo."},
    {palabra:"Cicatero", definicion:"Mezquino, ruin, miserable, que escatima lo que debe dar. / Que da importancia a pequeñas cosas o se ofende por ellas. / Reacio a gastar o compartir sus bienes, especialmente dinero. / Persona que tiene por costumbre u oficio el apropiarse de cosas que no le pertenecen."},
    {palabra:"A espuertas", definicion:"A montones, en abundancia."},
    {palabra:"Beodo", definicion:"Borracho."},
    {palabra:"Ecuménico", definicion:"Universal, que se extiende a todo el orbe."},
    {palabra:"Endo-", definicion:"Significa 'dentro', 'en el interior'. Endocardio, endógeno."},
    {palabra:"-Geno", definicion:"Significa 'que genera o produce' o 'que es producido'."},
    {palabra:"Perogrullada", definicion:"Verdad o certeza que, por notoriamente sabida, es necedad o simpleza el decirla."},
    {palabra:"Desiderátum", definicion:"Aspiración, deseo que aún no se ha cumplido. / El no va más."},
    {palabra:"Mancomunar", definicion:"Unir personas, fuerzas o caudales para un fin. / Unirse, asociarse, obligarse de mancomún."},
    {palabra:"Propalar", definicion:"Divulgar algo oculto."},
    {palabra:"Homeo-", definicion:"Significa 'semejante', 'parecido'."},
    {palabra:"-patia", definicion:"Significa 'sentimiento', 'afección' o 'dolencia'. Homeopatía, telepatía."},
    {palabra:"Visibilizar", definicion:"Hacer visible artificialmente lo que no puede verse a simple vista, como con los rayos X los cuerpos ocultos, o con el microscopio los microbios."},
    {palabra:"Párvulo", definicion:"Pequeño, inocente, cándido, sin malicia, humilde, apocado."},
    {palabra:"Meta-", definicion:"Significa 'junto a', 'después de', 'entre', 'con' o 'acerca de'."},
    {palabra:"Cuasi", definicion:"Casi."},
    {palabra:"Demudar", definicion:"Mudar, variar. / Alterar, disfrazar, desfigurar. / Cambiarse repentinamente el color, el gesto o la expresión del semblante."},
    {palabra:"Dirimir", definicion:"Resolver o solucionar un desacuerdo o una discusión. / Deshacer la unidad de un grupo."},
    {palabra:"Proto-", definicion:"Indica prioridad, preeminencia o superioridad."},
    {palabra:"Gnoseología", definicion:"Teoría del conocimiento. / Epistemología."},
    {palabra:"Determinar", definicion:"Decidir algo, despejar la incertidumbre sobre ello. / Establecer o fijar algo. / Señalar o indicar algo con claridad o exactitud."},
    {palabra:"Acémila", definicion:"Mula o macho de carga. / Asno, persona ruda."},
    {palabra:"Pico-", definicion:"Significa 'una billonésima (10−12) parte'."},
    {palabra:"Choteo", definicion:"Burla, pitorreo."},
    {palabra:"Desbrozar", definicion:"Quitar la broza, desembarazar, limpiar. / Eliminar los aspectos accesorios o confusos que complican un asunto innecesariamente y entorpecen su comprensión."},
    {palabra:"Exudar Exudación", definicion:"Dicho de un cuerpo: Dejar que salga por sus poros o sus grietas un líquido o una sustancia viscosa."},
    {palabra:"Iso-", definicion:"Significa 'igual'"},
    {palabra:"Isomorfo", definicion:"Dicho de dos o más cuerpos: Que, con diferente composición química, presentan igual estructura cristalina y pueden cristalizar asociados;"},
    {palabra:"Palíndromo", definicion:"Palabra o frase cuyas letras están dispuestas de tal manera que resulta la misma leída de izquierda a derecha que de derecha a izquierda; p. ej., anilina; dábale arroz a la zorra el abad."},
    {palabra:"Engranar", definicion:"Enlazar, trabar. / Dicho de dos ruedas dentadas: Encajar entre sí."},
    {palabra:"Sojuzgar", definicion:"Sujetar o dominar con violencia algo o a alguien."},
    {palabra:"Sibila", definicion:"Mujer sabia a quien los antiguos atribuyeron espíritu profético."},
    {palabra:"Bóvido", definicion:"Dicho de un mamífero: Del grupo de los rumiantes, carente de incisivos en la mandíbula superior y con ocho en la inferior, y con cuernos óseos no caedizos cubiertos por estuche córneo tanto en el macho como en la hembra"},
    {palabra:"Procaz", definicion:"Atrevido, desvergonzado."},
    {palabra:"Chamagoso", definicion:"Que no está limpio."},
    {palabra:"Poluto", definicion:"Sucio."},
    {palabra:"Taxonomía", definicion:"Ciencia que trata de los principios, métodos y fines de la clasificación. Se aplica en particular, dentro de la biología, para la ordenación jerarquizada y sistemática, con sus nombres, de los grupos de animales y de vegetales. / Clasificación."},
    {palabra:"Esquilmar", definicion:"Coger el fruto de las haciendas, heredades y ganados. / Dicho de una planta: Chupar con exceso el jugo de la tierra. / Menoscabar, agotar una fuente de riqueza sacando de ella mayor provecho que el debido."},
    {palabra:"Parvo", definicion:"Pequeño en tamaño, importancia o cantidad."},
    {palabra:"Adolecer", definicion:"Causar dolencia o enfermedad. / Caer enfermo o padecer alguna enfermedad habitual. / Tener o padecer algún defecto. / Compadecerse"},
    {palabra:"Ermita", definicion:"Causar dolencia o enfermedad. / Caer enfermo o padecer alguna enfermedad habitual. / Tener o padecer algún defecto. / Compadecerse"},
    {palabra:"Disforme", definicion:"Feo, horroroso, monstruoso. / Deforme."},
    {palabra:"Calígine", definicion:"Niebla, oscuridad, tenebrosidad."},
    {palabra:"Decaedro", definicion:"Sólido que tiene 10 caras."},
    {palabra:"Trapaza", definicion:"Artificio engañoso e ilícito con que se perjudica y defrauda a alguien en alguna compra, venta o cambio. / Fraude, engaño."},
    {palabra:"Demoscopia", definicion:"Estudio de las opiniones, aficiones y comportamiento humanos mediante sondeos de opinión."},
    {palabra:"Quiralidad", definicion:"Propiedad de quiral"},
    {palabra:"Quiral", definicion:"Dicho de una estructura o de un objeto: Que no es superponible con su imagen especular, asimétrico."},
    {palabra:"Dextrógiro", definicion:"Que gira en el sentido de las agujas del reloj."},
    {palabra:"Mesocrático", definicion:"Perteneciente o relativo a la clase media."},
    {palabra:"Mesocracia", definicion:"Sistema social en que la clase media es preponderante. / Clase media."},
    {palabra:"Ubérrimo", definicion:"Muy fértil"},
    {palabra:"Naftalina", definicion:"Naftaleno utilizado contra la polilla y como desinfectante."},
    {palabra:"Sinecdóque", definicion:"Designación de una cosa con el nombre de otra, de manera similar a la metonimia, aplicando a un todo el nombre de una de sus partes, o viceversa, a un género el de una especie, o al contrario, a una cosa el de la materia de que está formada, etc., como en cien cabezas por cien reses, en los mortales por los seres humanos, en el acero por la espada, etc."},
    {palabra:"Genericidad", definicion:"Cualidad de genérico."},
    {palabra:"Intensión", definicion:"Compresión. / Intensidad."},
    {palabra:"Conceptuar", definicion:"Formar concepto de algo o alguien."},
    {palabra:"Proselitistas", definicion:"Celoso de ganar prosélitos."},
    {palabra:"Prosélito", definicion:"Persona incorporada a una religión. / Partidario que se gana para una facción, parcialidad o doctrina."},
    {palabra:"Inquinar", definicion:"Manchar, contagiar."},
    {palabra:"Arribista", definicion:"Persona que progresa en la vida por medios rápidos y sin escrúpulos."},
    {palabra:"Redrar", definicion:"Arredrar (separar, apartar)"},
    {palabra:"Arredrar", definicion:"Retraer, hacer volver atrás, por el peligro que ofrece o el temor que infunde la ejecución de algo. / Amedrentar, atemorizar."},
    {palabra:"Indiano", definicion:"Alguien que llega rico de América."},
    {palabra:"Inequidad", definicion:"Desigualdad o falta de equidad."},
    {palabra:"Hediento", definicion:"Que despide mal olor."},
    {palabra:"Mefítico", definicion:"Dicho de una cosa: Que, respirada, puede causar daño, y especialmente cuando es fétida."},
    {palabra:"Colombofilia", definicion:"Técnica o afición a la cría, adiestramiento, cuidado, etc., de las palomas, en especial de las mensajeras."},
    {palabra:"Cáustico", definicion:"Dicho de una cosa: Que quema y destruye los tejidos animales. / Mordaz."},
    {palabra:"Inocular", definicion:"Introducir en un organismo una sustancia que contiene los gérmenes de una enfermedad. / Pervertir, contaminar a alguien con el mal ejemplo o la falsa doctrina."},
    {palabra:"Paladino", definicion:"Público, claro y patente."},
    {palabra:"Conníve", definicion:"Del inglés: Guiñar el ojo. / Disimular, fingir ceguedad e ignorancia tolerando o permitiendo algo."},
    {palabra:"Cianosis", definicion:"Coloración azul y alguna vez negruzca o lívida de la piel, debida a trastornos circulatorios."},
    {palabra:"Cianótico", definicion:"Perteneciente o relativo a la cianosis."},
    {palabra:"Lívido", definicion:"Amoratado. / Intensamente pálido."},
    {palabra:"Coadyuvar", definicion:"Contribuir o ayudar a que algo se realice o tenga lugar"},
    {palabra:"Coadyuvante", definicion:"Que coadyuva. / Persona que interviene en un proceso sosteniendo la pretensión de una de las partes."},
    {palabra:"Septicemia", definicion:"Infección generalizada producida por la presencia en la sangre de microorganismos patógenos o de sus toxinas."},
    {palabra:"Gargajear", definicion:"Arrojar gargajos."},
    {palabra:"Expeler", definicion:"Expulsar."},
    {palabra:"Deontología", definicion:"Parte de la ética que trata de los deberes, especialmente de los que rigen una actividad profesional. / Conjunto de deberes relacionados con el ejercicio de una determinada profesión."},
    {palabra:"Mondongo", definicion:"Estómago y tripas de un animal."},
    {palabra:"Erotomanía", definicion:"Deseo sexual exagerado o exacerbado en una persona."},
    {palabra:"Desproposito", definicion:"Dicho o hecho inoportuno e inconveniente."},
    {palabra:"-fagia", definicion:"Desgina la acción de comer o tragar."},
    {palabra:"Gehena", definicion:"Infierno o purgatorio judío, lugar de purificación para el malvado"},
    {palabra:"Denario", definicion:"Antigua moneda romana de plata."},
    {palabra:"Contumacia", definicion:"Actitud de una persona que se mantiene obstinadamente en un error."},
    {palabra:"Supra-", definicion:"Significa superior o encima (suprarrenal, supraestructura)"},
    {palabra:"Tripudo", definicion:"Que tiene mucha tripa."},
    {palabra:"Heraclida", definicion:"Descendiente de Heracles (Hércules), héroe griego, hijo de Zeus."},
    {palabra:"Loa", definicion:"Expresion o discurso con que se alaban las cualidades o los méritos de una persona o una cosa. / En el teatro clásico, prólogo o introducción con que solía iniciarse la representación."},
    {palabra:"Frenopatía", definicion:"Nombre que se daba antiguamente a la psiquiatría."},
    {palabra:"Merma", definicion:"Disminución o reducción del volumen o la cantidad de una cosa."},
    {palabra:"Prolapso", definicion:"Descenso o caída de un órgano interno, una víscera, etc., del cuerpo a causa de la relajación de sus medios de fijación. especialemnte cuando sale a tráves de un orificio natural o artificial."},
    {palabra:"Boyante", definicion:"Que se encuentra en una situación favorable, próspera o de felicidad."},
    {palabra:"Tartufo", definicion:"Hombre hipócrita y falso."},
    {palabra:"Detritus", definicion:"Resultado de la descomposición de una masa sólida en partículas."},
    {palabra:"Ínfula", definicion:"Resultad de la descomposición de una masa sólida en partículas. / Vanidad pretenciosa."},
    {palabra:"Sociopata", definicion:"Trastorno de personalidad antisocial, es una patología de índole psíquico que deriva en que las personas que la padecen pierden la noción de la importancia de las normas sociales, como son las leyes y los derechos individuales."},
    {palabra:"Resiliencia", definicion:"Capacidad de adaptación de un ser vivo frente a un agente perturbador o un estado o situación adversos. / Capacidad de un material, mecanismo o sistema para recuperar su estado inicial cuando ha cesado la perturbación a la que había estado sometido."},
    {palabra:"Departir", definicion:"Hablar, conversar. / Separar, repartir, dividir en partes. / Diferenciar, distinguir."},
    {palabra:"Arrabalero", definicion:"Que vive en los arrabales o periferias de las ciudades."},
    {palabra:"Respecto", definicion:"Razón, relación o proporción de algo a otra cosa."},
    {palabra:"Espinar", definicion:"Punzar. / Herir, lastimar y ofender con palabras picantes."},
    {palabra:"Veleidad", definicion:"Voluntad antojadiza o deseo vano. / Inconstancia, ligereza."},
    {palabra:"Emérito", definicion:"Dicho de una persona, especialmente de un profesor: Que se ha jubilado y mantiene sus honores y alguna de sus funciones. / En la Roma antigua, dicho de un soldado: Que había cumplido su tiempo de servicio y disfrutaba la recompensa debida a sus méritos."},
    {palabra:"Prominente", definicion:"Que se levanta o sobresale sobre lo que está a su inmediación o alrededores. / Ilustre, famoso, destacado."},
    {palabra:"Connivencia", definicion:"Disimulo o tolerancia en el superior acerca de las transgresiones que cometen sus subordinados contra las reglas o las leyes bajo las cuales viven. / Confabulación."},
    {palabra:"Inopinado", definicion:"Que sucede sin haber pensado en ello, o sin esperarlo."},
    {palabra:"Benzodiazepinas", definicion:"Las benzodiazepinas son medicamentos psicotrópicos que actúan sobre el sistema nervioso central, con efectos sedantes, hipnóticos, ansiolíticos, anticonvulsivos, amnésicos y miorrelajantes"},
    {palabra:"Savoir faire", definicion:"Destreza o gracia especial que tiene una persona para hacer las cosas, especialmente las relacionadas con el trato social."},
    {palabra:"Impeler", definicion:"Impulsar o hacer que una cosa o persona adquiera un movimiento rápido al aplicarle una fuerza. / Ejercer presión o influencia sobre una persona para que haga cierta cosa."},
    {palabra:"Apolíneo", definicion:"De Apolo (dios de las artes en la mitología griega) o relacionado con él. / Que responde al canon de belleza masculina."},
    {palabra:"Profesar", definicion:"Aceptar y seguir [una persona] voluntariamente una religión, una doctrina o una creencia. / Tener [una persona] una determinada inclinación o un sentimiento intenso hacia algo o alguien."},
    {palabra:"Sílfide", definicion:"Ninfa o espíritu elemental del aire de la mitología germánica. / Mujer que es muy esbelta y muy bella."},
    {palabra:"Herético", definicion:"Que contiene, implica o defiende herejías."},
    {palabra:"Subyugar", definicion:"Someter o dominar completamente a una persona o colectividad utilizando la persuasión. / Dominar [una pasión o un sentimiento, normalmente positivos] a alguien."},
    {palabra:"Alevosía", definicion:"Cautela para asegurar la comisión de un delito contra las personas, sin riesgo para el delincuente. Es circunstancia agravante de la responsabilidad criminal. / Traición, Perfidia."},
    {palabra:"Patria", definicion:"Tierra de los padres, la tierra paterna. / Tierra natal o adoptiva ordenada como nación, a la que se siente ligado el ser humano por vínculos jurídicos, históricos y afectivos."},
    {palabra:"Vernáculo", definicion:"Dicho especialmente del idioma o lengua: Doméstico, nativo, de la casa o país propios."},
    {palabra:"Lucutoso", definicion:"Triste, fúnebre y digno de llanto."},
    {palabra:"Silicosis", definicion:"Enfermedad crónica del aparato respiratorio que se produce por haber aspirado polvo de sílice en gran cantidad."},
    {palabra:"Óbito", definicion:"Muerte de una persona. / Deceso, defunción."},
    {palabra:"Deceso", definicion:"Muerte de una persona."},
    {palabra:"Polisémica", definicion:"Palabra que tiene varios significados."},
    {palabra:"Monosémica", definicion:"Palabra que tiene un único significado."},
    {palabra:"Parafilia", definicion:"Desviación sexual."},
    {palabra:"Inquina", definicion:"Aversión, mala voluntad."},
    {palabra:"Monacato", definicion:"Estado o profesión de monje. / Institución monástica."},
    {palabra:"Horda", definicion:"Comunidad de salvajes nómadas. / Grupo de gente que obra sin disciplina y con violencia."},
    {palabra:"Auspiciar", definicion:"Patrocinar, favorecer. / Presagiar, adivinar, predecir."},
    {palabra:"Homonización", definicion:"Proceso por el cual una raza de primates dio lugar a la especie humana."},
    {palabra:"Comicios", definicion:"Actos previos a una votación cuya finalidad es informar y convencer a los votantes de las ideas de una candidatura."},
    {palabra:"Motu Propio", definicion:"Voluntariamente o por propia iniciativa."},
    {palabra:"Auspiciar", definicion:"Patrocinio o ayuda que recibe una persona, una entidad, un proyecto, etc., para propiciar su desarrollo o su ejecución. / Señal o indicio que se interpreta como el anuncio de un hecho futuro, especialmente en relación con una actividad que se emprende."},
    {palabra:"Sepelio", definicion:"Ceremonia de inhumación o entierro de un cadaver."},
    {palabra:"Inhumar", definicion:"Enterrar un cadaver."},
    {palabra:"Displicente", definicion:"Que desplace, desagrada y disgusta. / Desdeñoso, descontentadizo, desabrido o de mal humor."},
    {palabra:"Proceloso", definicion:"Borrascoso, tormentoso, tempestuoso."},
    {palabra:"Sinapsis", definicion:"Conexión entre el axón de una neurona y la dendrita de otra cercana mediante neurotransmisores. / Relación funcional entre dos células. / Unión de dos cromosomas durante la profase."},
    {palabra:"Letanía", definicion:"Oración dialogada compuesta por una serie de súplicas o invocaciones breves a Dios o a los santos que una persona recita o canta y que las demás personas que participan en la oración repiten o contestan. / Lista o enumeración larga y monótona."},
    {palabra:"Séptico", definicion:"Que produce putrefacción o es causado por ella. / Que contiene gérmenes patógenos"},
    {palabra:"Patógeno", definicion:"Que origina y desarrolla una enfermedad"},
    {palabra:"Facineroso", definicion:"Delincuente habitual. / Que origina y desarrolla una enfermedad."},
    {palabra:"Contubernio", definicion:"Alianza o liga vituperable. / Habitación con otra persona. / Cohabitación ilícita."},
    {palabra:"Efigie", definicion:"Personificación, representación viva de un sentimiento. / Imagen o representación de una persona."},
    {palabra:"Frontispicio", definicion:"Fachada o delantera de un edificio, mueble u otra cosa. / Página de un libro anterior a la portada, que suele contener el título y algún grabado o viñeta. / Frontón."},
    {palabra:"Pecunio", definicion:"Peculio"},
    {palabra:"Peculio", definicion:"Dinero"},
    {palabra:"Sufete", definicion:"Cada uno de los dos magistrados supremos de Cartago y de otras repúblicas fenicias."},
    {palabra:"Inerme", definicion:"Sin armas. / Desprovisto de aguijones, pinchos o espinas."},
    {palabra:"Desabrir", definicion:"Dar mal gusto a la comida. / Disgustar, desazonar el ánimo de alguien. "},
    {palabra:"Sucedáneo", definicion:"Dar mal gusto a la comida. / Disgustar, desazonar el ánimo de alguien. "},
    {palabra:"Imprecar", definicion:"Proferir palabras con que se expresa el vivo deseo de que alguien sufra mal o daño."},
    {palabra:"Pedigón", definicion:"Que pide con frecuencia e inoportunidad. / Que pide, especialmente con insistencia."},
    {palabra:"Desgajar", definicion:"Desgarrar, arrancar, separar con violencia la rama del tronco de donde nace. / Despedazar, romper, deshacer algo unido y trabado. / "},
    {palabra:"Sincretismo", definicion:"Combinación de distintas teorías, actitudes u opiniones."},
    {palabra:"Hominización", definicion:"Proceso evolutivo, de primate a especie humana."},
    {palabra:"Pregnancia", definicion:"Cualidad de las formas visuales que captan la atención del observador por la simplicidad, equilibrio o estabilidad de su estructura."},
    {palabra:"Tropismo", definicion:"Tendencia de un organismo a reaccionar de una manera determianda a los estímulos exteriores."},
    {palabra:"Escópico", definicion:"Visual, 'con la mirada'. Se usa con frecuencia en el psicoanálisis y en las artes visuales."},
    {palabra:"Pulsión", definicion:"Impuslo. En psicoanálisis fuerza que impulsa al sujeto a llevar a cabo una acción."},
    {palabra:"Príapo", definicion:"Pene, especialmente el del hombre."},
    {palabra:"Meandro", definicion:"Cada una de las curvas que describe el curso de un río. Adorno de líneas sinuosas y repetidas."},
    {palabra:"Sosiego", definicion:"Calma, tranquilidad, quietud, paz, placidez."},
    {palabra:"Abrevadero", definicion:"Lugar donde abreva el ganado."},
    {palabra:"Abrevar", definicion:"Beber, especialmente los animales."},
    {palabra:"Remora", definicion:"Obstáculo físico o inmaterial que impide un proceso, un proyecto o una acción."},
    {palabra:"Mitosis", definicion:"Proceso de reproducción de una célula que consiste en la división de los cromosomas y en la división del núcleo."},
    {palabra:"Ameba", definicion:"Una protista unicelular del género Amoeba. Es un protozoo caracterizado por su forma cambiante, puesto que carece de pared celular, y por su movimiento ameboide a base de seudópodos"},
    {palabra:"Elucubrar", definicion:"Reflexionar a cerca de algo con atención y cuidado para estudiarlo o comprenderlo bien o para llegar a alguna conclusión."},
    {palabra:"Acre", definicion:"Áspero y picante al gusto y al olfato, como el sabor y el olor del ajo, del fósforo, etc."},
    {palabra:"Verba volant scripta manent", definicion:"Cita latina de Cayo Tito: 'Las palabras vuelan, lo escrito queda.'"},
    {palabra:"Truculento", definicion:"Que sobrecoge o asusta por su morbosidad, exagerada crueldad o dramatismo."},
    {palabra:"Eminentemente", definicion:"Predominantemente. Que tiene un grado superior."},
    {palabra:"Siliente", definicion:"Silencioso."},
    {palabra:"Polonio 210", definicion:"Se trata de un raro metaloide altamente radiactivo"},
    {palabra:"Histriónico", definicion:"Perteneciente o relativo al histrión."},
    {palabra:"Histrión", definicion:"Actor teatral. / Persona que se expresa con afectación o exageración propia de un actor teatral. / Prestidigitador, acróbata o cualquier otra persona que divertía al público con disfraces. / Hombre que representaba disfrazado en la comedia o tragedia antigua."},
    {palabra:"Irredento", definicion:"Dicho especialmente del territorio que una nación pretende anexionarse por razones históricas, de lengua, raza, etc.: Que permanece sin redimir."},
    {palabra:"Redimir", definicion:"Rescatar o sacar de esclavitud al cautivo mediante precio. / Comprar de nuevo algo que se había vendido, poseído o tenido por alguna razón o título. / Librar de una obligación o extinguirla."},
    {palabra:"Pírrico", definicion:"Dicho de un triunfo o de una victoria: Obtenidos con más daño del vencedor que del vencido. / Conseguido con mucho trabajo o por un margen muy pequeño. / De poco valor o insuficiente, especialmente en proporción al esfuerzo realizado. / Dicho de una danza: Practicada en la Grecia antigua y que imitaba un combate."},
    {palabra:"Disgenesia", definicion:"Disgenesia es un término opuesto a la eugenesia, y es utilizado por algunos científicos actuales para caracterizar la selección de variables genéticas negativas."},
    {palabra:"Eugenesia", definicion:"Aplicación de las leyes biológicas de la herencia al perfeccionamiento de la especie humana."},
    {palabra:"Divergente", definicion:"Que diverge, que se separa en dos líneas. / Discordar, discrepar."},
    {palabra:"Discordante", definicion:"Que está en desacuerdo con otra u otras personas o cosas. / Que no guarda consonancia armónica con los demás sonidos de un conjunto."},
    {palabra:"Medianía", definicion:"Vulgar, del montón. / Condición de ser medio, mediano o promedio. / Por extensión, cosa o persona sin defectos o virtudes notorias"},
    {palabra:"Peccata minuta", definicion:"Lat. Pequeño pecado. / Expresión latina familiar que se usa para indicar un error o falta leve. Se usa en sentido coloquial para designar una culpa, equivocación o error de poca importancia. / Se usa para referirse a algo sin importancia o de poco valor. 'Lo que ha hecho este hombre es peccata minuta, en comparación con lo que han hecho otros.'"},
    {palabra:"Mindfulness", definicion:"La atención plena, conciencia plena o conciencia pura; también traducido como conciencia es una facultad espiritual o psicológica que se consideran de gran importancia en el camino hacia la iluminación"},
    {palabra:"Epítome", definicion:"Resumen de un discurso extenso en unas pocas palabras finales. / Resumen o compendio de una obra extensa, que expone lo fundamental o más preciso de la materia tratada en ella."},
    {palabra:"Verbosidad", definicion:"Abundancia de palabras en la elocución."},
    {palabra:"Elocución", definicion:"Manera de hablar y manejar los conceptos. / Modo de elegir y distribuir los pensamientos y las palabras en el discurso."},
    {palabra:"Habitud", definicion:"Relación que tiene una cosa respecto de otra. / Relación que tiene una cosa con otra."},
    {palabra:"Locuacidad", definicion:"Cualidad de locuaz."},
    {palabra:"Locuaz", definicion:"Que habla mucho o demasiado. / Loco."},
    {palabra:"Ávido", definicion:"Ansioso, codicioso."},
    {palabra:"Embelesar", definicion:"Arrebatar o cautivar los sentidos."},
    {palabra:"Habitud", definicion:"Relación que tiene una cosa respecto de otra. / Hábito, costumbre."},
    {palabra:"Disforia", definicion:"La disforia se caracteriza generalmente como una emoción desagradable o molesta, como la tristeza, ansiedad, irritabilidad o inquietud. Es el opuesto etimológico de la euforia."},
    {palabra:"Fraseología", definicion:"Conjunto de modos de expresión peculiares de una lengua, de un grupo, de una época, actividad o individuo. / Conjunto de expresiones intrincadas, pretenciosas o falaces. / Palabrería."},
    {palabra:"Facundia", definicion:"Facilidad y desenvoltura en el hablar."},
    {palabra:"Astracanada", definicion:"Acción o comportamiento públicos disparatados y ridículos."},
    {palabra:"Exhortar", definicion:"Incitar o actuar mediante razones o ruegos."},
    {palabra:"Exabrupto", definicion:"Salida de tono o ademán inesperado con viveza."},
    {palabra:"Dialectal", definicion:"Relativo del dialecto."},
    {palabra:"Arameo", definicion:"Perteneciente a un pueblo semítico."},
    {palabra:"Esperanto", definicion:"Lengua que fue creada para convertirse en una lengua auxiliar internacional, crada por un oftalmólog Polaco."},
    {palabra:"Sofisticar", definicion:"Falsificar o corromper algo."},
    {palabra:"Fluctuación", definicion:"Oscilar. / Duda, irresolución o indeterminación. /  Dicho de una cosa: correr el riesgo de perderse y aurrinarse"},
    {palabra:"Punición", definicion:"Castigo."},
    {palabra:"Vesícula", definicion:"Vegija. / Abultamiento que aparece en la piel en forma de bolsa pequeña llena de liquido, a causa de una quemadura, roce o enfermedad."},
    {palabra:"Seráfico", definicion:"Angelical."},
    {palabra:"Presbicia", definicion:"Vista cansada."},
    {palabra:"Proléptico", definicion:"Conocimiento anticipado de una cosa, en la doctrina de los epicúreos y los estoicos."},
    {palabra:"Acucia", definicion:"Diligencia, solicitud, prisa. / Deseo vehemente."},
    {palabra:"Bluf", definicion:"Montaje propagandístico para crear un prestigio falso. / Fanfarronada."},
    {palabra:"Prurito", definicion:"Deseo persistente y excesivo de hacer algo de la mejor manera posible."},
    {palabra:"Egotismo", definicion:"Prurito de hablar de sí mismo. / Sentimiento exagerado de la propia personalidad."},
    {palabra:"Abigarrado", definicion:"Heterogéneo, reuinido sin concierto."},
    {palabra:"Heterogéneo", definicion:"Compuesto de partes de diversa naturaleza."},
    {palabra:"Trepidar", definicion:"Temblar fuertemente."},
    {palabra:"Filia", definicion:"Amor o afición por algo."},
  
  ];

}]);


